### PR TITLE
wihslist item

### PR DESCRIPTION
**Pull request by giretyu**
### What problem is this solving?

https://tfginfotec.atlassian.net/browse/BPF-1608

wishlist ungrouping
### How it works:

https://github.com/TFG-Labs/wish-list/assets/98810994/c2492222-c21d-480b-a575-8c2b71c45047

#### How to test it?
Provide sufficient enough information for a non developer to test 
Workspace
https://bpf1608v3--thefoschini.myvtex.com/oxford
### Coding Standards Checklist: https://tfginfotec.atlassian.net/l/c/60ZyZonH
- [ ] [BlockClass principles]( https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#Block-Classes)
- [ ] [Block name principles]( https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#Block-Names?)
- [ ] [Folder Structure principles ](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#JSON-Folder-Structure)
- [ ] [CSS folder principles](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#CSS-Folder-Structure)
- [ ] [JSONC files principles](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#JSONC-File-Structure)
- [ ] [CSS file principles](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#CSS-file-structure)
- [ ] S[tyle tokens and SCSS]( https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#STYLE-TOKENS-AND-SCSS)
- [ ] [Code comments](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#STYLE-TOKENS-AND-SCSS)
- [ ] [Responsibility to maintain code](https://tfginfotec.atlassian.net/wiki/spaces/LABSPLAT/pages/1711341597/Styleguide+and+Code+Organisation+Principles#Responsibility-to-Maintain-The-Code-Quality)

### How does this PR make you feel? 🔗

### CODE REVIEW

**Review by simmbiote — CHANGES_REQUESTED** [review]
Hey @giretyu can we improve the removing from wishlist?
Scenario: I want to add both a S and a XXXXXL jersey to my wishlist.
Problem: When I try to add XXXXXL jersey, it removes the S instead.

If it's easy: ensure removing removes the selected Sku only.
If it's not: can we just disable remove from wishlist at PDP? Customer then needs to remove via Wishlist screen.

image

**Review by simmbiote — CHANGES_REQUESTED** [review]
Can we also see the SKU attributes here - Size/Colour:
I guess that would be in the other repo.

image

**Comment by giretyu** [comment]
@simmbiote  added Size/Colour
[
Screenshot 2023-10-10 at 14 23 48
](url)

**Review by lezegom — APPROVED** [review]

**Review by simmbiote — APPROVED** [review]
Awesome 🎸

**Pull request merged**
